version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/db/sqlite.db
      - JWT_SECRET=${JWT_SECRET}
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_KEY=${MEILISEARCH_MASTER_KEY}
      - BOOKS_STORAGE_PATH=/app/data/books
      - ORIGIN=${ORIGIN:-http://localhost:3000}
    volumes:
      - ./data:/app/data
    depends_on:
      - meilisearch
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
      - MEILI_ENV=production
    volumes:
      - ./data/meili_data:/meili_data
    restart: unless-stopped

volumes:
  data:

