services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000
    networks:
      - dokploy-network
    labels:
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-web.rule=Host(`books.phelddagrif.farm`)
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-web.entrypoints=web
      - traefik.http.services.phelddagriffarm-pagedrift-cknlcf-web.loadbalancer.server.port=7000
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-web.service=phelddagriffarm-pagedrift-cknlcf-web
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-web.middlewares=redirect-to-https@file
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-websecure.rule=Host(`books.phelddagrif.farm`)
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-websecure.entrypoints=websecure
      - traefik.http.services.phelddagriffarm-pagedrift-cknlcf-websecure.loadbalancer.server.port=7000
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-websecure.service=phelddagriffarm-pagedrift-cknlcf-websecure
      - traefik.http.routers.phelddagriffarm-pagedrift-cknlcf-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
    environment:
      - NODE_ENV=production
      - PORT=7000
      - DATABASE_URL=file:/app/data/db/sqlite.db
      - JWT_SECRET=${JWT_SECRET}
      - MEILISEARCH_HOST=${MEILISEARCH_HOST:-http://meilisearch:7700}
      - MEILISEARCH_KEY=${MEILISEARCH_MASTER_KEY}
      - BOOKS_STORAGE_PATH=/app/data/books
    volumes:
      - ebook_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  ebook_data:
    external: false
    name: phelddagrif_ebook_data

networks:
  dokploy-network:
    external: true
