version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000
    networks:
      - dokploy-network
    labels:
      - traefik.http.routers.pagedrift-web.rule=Host(`books.phelddagrif.farm`)
      - traefik.http.routers.pagedrift-web.entrypoints=web
      - traefik.http.routers.pagedrift-web.middlewares=redirect-to-https@file
      - traefik.http.routers.pagedrift-websecure.rule=Host(`books.phelddagrif.farm`)
      - traefik.http.routers.pagedrift-websecure.entrypoints=websecure
      - traefik.http.routers.pagedrift-websecure.tls.certresolver=letsencrypt
      - traefik.http.services.pagedrift-web.loadbalancer.server.port=7000
      - traefik.enable=true
    environment:
      - NODE_ENV=production
      - PORT=7000
      - DATABASE_URL=file:/app/data/db/sqlite.db
      - JWT_SECRET=${JWT_SECRET}
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_KEY=${MEILISEARCH_MASTER_KEY}
      - BOOKS_STORAGE_PATH=/app/data/books
      - ORIGIN=${ORIGIN:-http://localhost:3000}
    volumes:
      - ./data:/app/data
    depends_on:
      meilisearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7000/api/auth/me"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - 7700
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
      - MEILI_ENV=production
    volumes:
      - ./data/meili_data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7700/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - dokploy-network

volumes:
  data:

networks:
  dokploy-network:
    external: true
