# Nixpacks configuration for Dokploy deployment
# This file explicitly defines the build and start process for the application

[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm ci", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma migrate deploy && node build"

